### ISSUE TITLE
Third letter of the Language you are leaning.  'a' should work, but only 'A' is accepted.

### ISSUE THREAD

**Issue by ryandavidhartman** [alejandrolujan/scalaquest-bugs#11]

**Comment by ryandavidhartman** [comment]
I see https://github.com/alejandrolujan/scalaquest-bugs/issues/3 is a related issue.

**Comment by eduardoverde** [comment]
We've fixed the 'world' typo and added a new hint to remind the player we are expecting an uppercase letter.
Thanks for the report!
