### ISSUE TITLE
Store the set of all vowels in the val vowels, with the appropriate data type annotation

### ISSUE THREAD

**Issue by ryandavidhartman** [alejandrolujan/scalaquest-bugs#12]
why not accept:
val vowels: Set[Char] = Set('a','e', 'i', 'o', 'u', 'y')

'y' can be considered a vowel

**Comment by alejandrolujan** [comment]
Related to #6

**Comment by eduardoverde** [comment]
We've found a solution to this. Now the game shows a hint asking specifically for the five vowels 'a', 'e', 'i', 'o' and 'u'.
Thanks for the report!
