### ISSUE TITLE
Chapter 2 Final Puzzle

### ISSUE THREAD

**Issue by ryandavidhartman** [alejandrolujan/scalaquest-bugs#17]
POST http://game.scalaquest.com/solution?l=2 400 (Bad Request)

`{"TestFailures":{"message":"Ugh! Your code did not pass our tests","failures":[]}}`

is returned, with nothing in the list of failures.

Here was my input
```scala
class Piece(val resistance:Int, val currentLoad:Int) {
    def this(p:Piece) = this(p.resistance, 0)
    def collapsed = currentLoad > resistance
    def +(load:Int) = new Piece(resistance, currentLoad + load)
    def -(load:Int) = new Piece(resistance, currentLoad - load)
    override def equals(other:Any):Boolean = {
        val p:Piece = other.asInstanceOf[Piece]
        p.resistance == resistance && p.currentLoad == currentLoad
    }
    override def hashCode: Int = {
        resistance + currentLoad*1131
    }
}
```

**Comment by GrosseBen** [comment]
so we also can't reach the next Level
:,,-)

<img width="1386" alt="bildschirmfoto 2018-04-01 um 13 21 46" src="https://user-images.githubusercontent.com/3909960/38172727-ddfbee66-35b1-11e8-88f3-4e95e9fcc230.png">

**Comment by JoelBushart** [comment]
collapsed should be a field not a method

**Comment by JoelBushart** [comment]
what happens if I call equals and pass in an Int?

**Comment by GrosseBen** [comment]
Good argument ;-)
I think this would be a nice Hint 👍 

But:
![bildschirmfoto 2018-04-12 um 22 54 04](https://user-images.githubusercontent.com/3909960/38703887-ccb08440-3ea4-11e8-9851-a0e1ffef7ff3.png)

**Comment by eduardoverde** [comment]
Hey guys. We've made some fixes here.
If you are still stuck at level 2 you can try again.
Please let us know how it goes.
