### ISSUE TITLE
Enter key not working in Firefox

### ISSUE THREAD

**Issue by eduardoverde** [alejandrolujan/scalaquest-bugs#18]
In Firefox, pressing enter only seems to work on screens with the text box. When the player initially goes
to a gem or finish some questions enter does nothing. The player needs to click
the "x", but when there's a textbox pressing Enter does send the answer and
move to the next question.

**Comment by alejandrolujan** [comment]
@eduardoverde I can't verify this on my environment. Enter works fine on Firefox in mac OS High Sierra.

Can you please try Firefox on Windows, see if you get the same behaviour?

**Comment by alejandrolujan** [comment]
We cannot replicate this - will reopen if we get more details to validate.
