### ISSUE TITLE
Cannot unlock the door in level 1 - http 500 error

### ISSUE THREAD

**Issue by jona7o** [alejandrolujan/scalaquest-bugs#2]
Hi, 

i tried the following as solution:

`
val until = 7
var count = 0
while(count <= until){
    if(count % 2 == 1){
        println("pull")
    }else{
        println("turn")
    }
    count = count + 1
}
`

but the only thing what happens is that the text is flickering
"You jiggle and joggle the handle, hoping it will unlock"

![bildschirmfoto 2018-02-16 um 15 48 09](https://user-images.githubusercontent.com/8403631/36313101-d5eceef8-1330-11e8-87c5-8d5e6aa3d905.png)

**Comment by egp** [comment]
I also failed to get through the door with very similar code. It never failed, just kept trying

**Comment by alejandrolujan** [comment]
We found an issue with the final challenge in our deployed app - fix coming up soon!

**Comment by alejandrolujan** [comment]
This has just been fixed, thanks for the report!
