### ISSUE TITLE
Needs soundtrack ! 

### ISSUE THREAD

**Issue by sebastianharko** [alejandrolujan/scalaquest-bugs#5]
I don't hear anything (maybe it's Safari's fault ? )... Anyway, this game needs serious music.

**Comment by alejandrolujan** [comment]
Sebastian, can you try on another browser? You should hear a background track and several sound effects :)

I just tried on Safari, and you're totally right, no sounds at all. We'll take a look at this.

**Comment by dholtz** [comment]
I wouldn't mind having a mute button as well for the music and the sound effects.
I don't want to have to mute all sound.

**Comment by eduardoverde** [comment]
After some research, it looks like we won't be supporting audio on Safari in the near future.  We've just added a message to alert the users this is happening on Safari.
Thanks a lot for your report. We'll revisit this at a later time, but for now, you can either play without audio or switch to a different browser.
