### ISSUE TITLE
3rd Gem Vowel order is particular

### ISSUE THREAD

**Issue by davidgraig** [alejandrolujan/scalaquest-bugs#6]
Attempt to solve the 3rd gem puzzle like: `val vowels: Set[Char] = Set('a', 'i', 'e', 'o', 'u')` is a valid submission

Expected Outcome: success
Actual Outcome: a hint comes up, no success.

![image](https://user-images.githubusercontent.com/851818/36328923-da216e3a-1318-11e8-8a2d-52e5a2d1944d.png)

note that `val vowels: Set[Char] = Set('a', 'e', 'i', 'o', 'u')` succeeds.

**Comment by kyrsideris** [comment]
I second that. My answer was
```scala
val vowels: Set[Char] = Set('a', 'e', 'o', 'i', 'u')
```
which shouldn't have failed.

**Comment by fkorling** [comment]
What about 'y'? Maybe it's not seen as an English vowel but Wikipedia says: 

> These letters are vowels in English:
> 
> A, E, I, O, U, and sometimes Y.

(from https://simple.wikipedia.org/wiki/Vowel)

**Comment by alejandrolujan** [comment]
Great catch - fix coming up soon!

**Comment by eduardoverde** [comment]
Fixed. Now the vowels order is more flexible.
Thanks for the report!

**Comment by eduardoverde** [comment]
Related to #12
