### ISSUE TITLE
2nd Gem Puzzle cannot be solved

### ISSUE THREAD

**Issue by davidgraig** [alejandrolujan/scalaquest-bugs#7]
Attempt to solve 2nd puzzle with any of:

- `val multiple = "lastName".contains(' ')`
- `val multiple: Boolean = "lastName".contains(' ')`

Expected: success
Actual: no success, a hint pops up

![image](https://user-images.githubusercontent.com/851818/36329108-a7d6b240-1319-11e8-969c-dcbe42bee05b.png)

output from scala console:  

```
scala> val multiple = "lastName".contains(' ')
multiple: Boolean = false
```

**Comment by mdenison** [comment]
Have you tried 
``val multiple = lastName.contains(' ')
I thought it was quite intuitiv when it said "the value lastName" that lastname is already defined.

**Comment by davidgraig** [comment]
hahahah oh! i misread it. `String value lastName` vs `a string with value "lastName"` i suppose.  resolved!
