### ISSUE TITLE
Wrong answer or hints not clear.

### ISSUE THREAD

**Issue by yagoff** [alejandrolujan/scalaquest-bugs#8]
For me this is an infinite loop and it should not ever complete, but it expects a "Yes" as an answer. If it does complete I think the Hints should be more clear specifying why.
![captura de pantalla de 2018-02-17 12-00-54 png](https://user-images.githubusercontent.com/9529767/36340334-2f2d0dea-13db-11e8-895d-48f611dc5318.png)

**Comment by alejandrolujan** [comment]
Good catch - our solution is just incorrect! Fix coming up.

**Comment by eduardoverde** [comment]
Done! We have fixed the solution for this challenge. Thanks for the report.
